project:
  type: website
  execute-dir: project
  render: # Add HERE new chapters and new notebooks
    - index.qmd
    - notebooks/dataSource.qmd
    - notebooks/ModelApproach.qmd
    - notebooks/Results.qmd
    - notebooks/currentResearch.qmd
    #- chapters/chapter1.qmd
    #- notebooks/notebook1.qmd

website:
  page-navigation: true
  title: "AIML4OS WP10 - Cluster 2"
  # In the two URLs below:
  # - replace AIML4OS by the Github account/organization your repository is hosted by;
  # - replace AIML4OS-template-quarto-python by the name of your repository.
  # If your repo is on the AIML4OS organization, change only the name of the repo.
  site-url: "https://AIML4OS.github.io/WP10_Cluster2_NACEClassification_PL"
  repo-url: "https://github.com/AIML4OS/WP10_Cluster2_NACEClassification_PL"
  repo-actions: [edit, source, issue]
  sidebar:
    search: true
    contents: # Add HERE new chapters (but not the notebooks)
      - href: index.qmd
        text: Introduction
      - href: notebooks/dataSource.qmd
        text: Data source
      - href: notebooks/ModelApproach.qmd
        text: Model Approach
      - href: notebooks/Results.qmd
        text: Results
      - href: notebooks/currentResearch.qmd
        text: Current research

format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true
    code-fold: true
  ipynb:
    output: true


filters:
  - export-metadata.lua

